package com.aoe4.randomizer.persistence;

import org.h2.tools.RunScript;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseManager {
    private static final String USERNAME = "sa";
    private static final String PASSWORD = "";
    private static final String DATA_DIRECTORY_PROPERTY = "aoe4.randomizer.dataDir";
    private static final String DATABASE_FILE_NAME = "aoe4randomizer";

    private final String jdbcUrl;

    public DatabaseManager(Path dataDirectory) {
        try {
            Files.createDirectories(dataDirectory);
        } catch (IOException ex) {
            throw new IllegalStateException("Could not create data directory: " + dataDirectory, ex);
        }
        this.jdbcUrl = "jdbc:h2:file:" + dataDirectory.resolve(DATABASE_FILE_NAME).toAbsolutePath().toString().replace('\\', '/');
    }

    public static DatabaseManager createDefault() {
        String configuredDirectory = System.getProperty(DATA_DIRECTORY_PROPERTY);
        if (configuredDirectory != null && !configuredDirectory.isBlank()) {
            return new DatabaseManager(Path.of(configuredDirectory.trim()));
        }
        return new DatabaseManager(Path.of(System.getProperty("user.home"), ".aoe4-civ-randomizer", "data"));
    }

    public void initialize() {
        try (Connection connection = openConnection()) {
            createSchema(connection);
            seedData(connection);
        } catch (SQLException | IOException ex) {
            throw new IllegalStateException("Failed to initialize database", ex);
        }
    }

    public Connection openConnection() throws SQLException {
        return DriverManager.getConnection(jdbcUrl, USERNAME, PASSWORD);
    }

    private void createSchema(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS civilization (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL UNIQUE,
                        dlc VARCHAR(255) NOT NULL,
                        icon_path VARCHAR(255),
                        enabled BOOLEAN NOT NULL DEFAULT TRUE
                    )
                    """);
        }
    }

    private void seedData(Connection connection) throws IOException, SQLException {
        try (InputStream stream = DatabaseManager.class.getResourceAsStream("/data.sql")) {
            if (stream == null) {
                throw new IllegalStateException("Could not find data.sql on the classpath");
            }
            try (Reader reader = new InputStreamReader(stream, StandardCharsets.UTF_8)) {
                RunScript.execute(connection, reader);
            }
        }
    }
}
